server:
    port: 9898
    context-path: #/liuzh/

#logging:
#    level:
#        org.springframework: DEBUG
#        com.fz.mapper.BookMapper: DEBUG
#        com.fz.utils.BaseMapper: DEBUG
#    file:
#        logs/spring-boot-logging.log

configure:
    decompPath: /Users/georgezou/Documents/WORK/DEMO/gz-epub/    # 解压路径
#     decompPath: /home/founder/apache-tomcat-7.0.6/webapps/epub/
    webServerPath: test/books/                                   # 解压后的文件相对于web服务器的路径
     # decompPath: D:\\founder\\tomcat-6.0.20\\webapps\\
     # webServerPath: epub\\test\\books\\

spring:
    datasource:
#        url: jdbc:sqlserver://192.168.16.200:1433;DatabaseName=test
#        username: sa
#        password: 123456
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        name: test
        url: jdbc:mysql://127.0.0.1:3306/epub?useUnicode=true&characterEncoding=utf8
        # url: jdbc:mysql://192.168.0.5:3306/epub?useUnicode=true&characterEncoding=utf8
        # url: jdbc:mysql://10.0.65.107:3305/epub?useUnicode=true&characterEncoding=utf8
        # url: jdbc:mysql://182.92.11.96:3306/epubreader?useUnicode=true&characterEncoding=utf8
        # url: jdbc:mysql://192.168.0.5:3306/epub?useUnicode=true&characterEncoding=utf8
        # url: jdbc:mysql://172.16.8.243:3306/epub?useUnicode=true&characterEncoding=utf8
        username: root
        password: TFMysql02
        # password: newpass
        # password: founder123
        # password: Founder123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
#    freemarker:
#        cache: false
#        request-context-attribute: request

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
